version: '3.8'

#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16

x-hosts:
  &default-hosts
  extra_hosts:
    - rabbit-1:${IP_ADDR_PREFIX}.41
    - rabbit-2:${IP_ADDR_PREFIX}.42
    - rabbit-3:${IP_ADDR_PREFIX}.43


