version: '3.8'

#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16

#services:
#  haproxy:
#    container_name: rabbit-haproxy
#    image: ${HAPROXY_IMAGE}
#    hostname: rabbit-haproxy.shit-code.com
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.40
#    #    command: ["-f","/usr/local/etc/haproxy/haproxy.cfg"]
#    ports:
#      - 1080:1080
#    volumes:
#      - ${DOCKER_CONFIG}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg