version: '3.8'

#consul集群配置
services:
  consul-1: &consul
    container_name: consul-1
    image: ${CONSUL_IMAGE}
    hostname: consul-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent",  "-config-dir", "/consul/config"]
    extra_hosts:
      - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
      - consul-2.shit-code.com:${IP_ADDR_PREFIX}.12
      - consul-3.shit-code.com:${IP_ADDR_PREFIX}.13
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-2:
    <<: *consul
    container_name: consul-2
    hostname: consul-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.12
    volumes:
      - ${DOCKER_VOLUME}/consul/node2:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-3:
    <<: *consul
    container_name: consul-3
    hostname: consul-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.13
    volumes:
      - ${DOCKER_VOLUME}/consul/node3:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json