version: '3.8'

#consul集群配置
services:
  consul-1:
    &consul
    environment:
      - TZ=${TIME_ZONE}
    extra_hosts:
      - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
      - consul-2.shit-code.com:${IP_ADDR_PREFIX}.12
      - consul-3.shit-code.com:${IP_ADDR_PREFIX}.13
    container_name: consul-1
    image: ${CONSUL_IMAGE}
    hostname: consul-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent", "-config-dir", "/consul/config"]
    volumes:
      - consul_volume_1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-2:
    <<: *consul
    container_name: consul-2
    hostname: consul-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.12
    volumes:
      - consul_volume_2:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-3:
    <<: *consul
    container_name: consul-3
    hostname: consul-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.13
    volumes:
      - consul_volume_3:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  git2consul:
    depends_on:
      - consul-1
      - consul-2
      - consul-3
    container_name: git2consul
    image: cimpress/git2consul
    hostname: git2consul.shit-code.com
    command: ['--endpoint','consul-1.shit-code.com','--port','8500','--config-file','/etc/git2consul.d/config.json']
    extra_hosts:
      - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
      - consul-2.shit-code.com:${IP_ADDR_PREFIX}.12
      - consul-3.shit-code.com:${IP_ADDR_PREFIX}.13
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.19
    volumes:
      - ${DOCKER_CONFIG}/git2consul/config.json:/etc/git2consul.d/config.json

volumes:
  consul_volume_1:
  consul_volume_2:
  consul_volume_3: