version: '3.8'

#mysql集群
services:
  mysql-master:
    &mysql
    extra_hosts:
      - mysql-master.shit-code.com:${IP_ADDR_PREFIX}.21
      - mysql-slave.shit-code.com:${IP_ADDR_PREFIX}.22
    container_name: mysql-master
    image: ${MYSQL_IMAGE}
    hostname: mysql-master.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.21
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    #      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_CONFIG}/mysql/master.cnf:/etc/mysql/conf.d/master.cnf
      - mysql_volume_master:/var/lib/mysql
  mysql-slave:
    <<: *mysql
    container_name: mysql-slave
    hostname: mysql-slave.shit-code.com
    depends_on:
      - mysql-master
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.22
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_CONFIG}/mysql/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - mysql_volume_slave:/var/lib/mysql
volumes:
  mysql_volume_master:
  mysql_volume_slave:

# mysqldb里面的host要用ip
#  eithi9ram2Saeji5Nai7miShohzop2Uc
#  nav9ahdong5NohNgoopooSh4eideijoo
# sudo grep 'GENERATED ROOT PASSWORD' /var/lib/mysql/mysql_master.log
# master
#  ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourPassword';
# CREATE USER 'slave'@'172.28.2.22' IDENTIFIED WITH mysql_native_password BY '123456';
# GRANT REPLICATION SLAVE ON *.* TO 'slave'@'172.28.2.22';
# CREATE USER 'username'@'host' IDENTIFIED WITH mysql_native_password BY 'password';
# GRANT Create,drop,insert,update,delete ON *.* TO 'username'@'host';
# show master status;

# flush privileges;

# slave
# CHANGE MASTER TO MASTER_HOST='172.28.2.21',MASTER_USER='slave',MASTER_PASSWORD='123456',MASTER_LOG_FILE='master_binlog.000003',MASTER_LOG_POS=1221;
# show slave status\G

#  CREATE USER 'exporter'@'%' IDENTIFIED BY '123456';
#  GRANT PROCESS, REPLICATION CLIENT ON *.* TO 'exporter'@'%';
#  GRANT SELECT ON performance_schema.* TO 'exporter'@'%';