version: '3.8'

#redis集群配置
services:
  redis-1:
    &redis
    extra_hosts:
      - redis-1.shit-code.com:${IP_ADDR_PREFIX}.31
      - redis-2.shit-code.com:${IP_ADDR_PREFIX}.32
      - redis-3.shit-code.com:${IP_ADDR_PREFIX}.33
      - redis-4.shit-code.com:${IP_ADDR_PREFIX}.34
      - redis-5.shit-code.com:${IP_ADDR_PREFIX}.35
      - redis-6.shit-code.com:${IP_ADDR_PREFIX}.36
    container_name: redis-1
    image: ${REDIS_IMAGE}
    hostname: redis-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.31
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_volume_1:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-2:
    <<: *redis
    container_name: redis-2
    hostname: redis-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.32
    volumes:
      - redis_volume_2:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-3:
    <<: *redis
    container_name: redis-3
    hostname: redis-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.33
    volumes:
      - redis_volume_3:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-4:
    <<: *redis
    container_name: redis-4
    hostname: redis-4.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.34
    volumes:
      - redis_volume_4:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-5:
    <<: *redis
    container_name: redis-5
    hostname: redis-5.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.35
    volumes:
      - redis_volume_5:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-6:
    <<: *redis
    container_name: redis-6
    hostname: redis-6.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.36
    volumes:
      - redis_volume_6:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  redis_volume_1:
  redis_volume_2:
  redis_volume_3:
  redis_volume_4:
  redis_volume_5:
  redis_volume_6:
#  redis-cli --cluster create 172.28.0.31:6379 172.28.0.32:6379 172.28.0.33:6379 172.28.0.34:6379 172.28.0.35:6379 172.28.0.36:6379 --cluster-replicas 1
