version: '3.8'

services:
  rabbit_haproxy:
    container_name: rabbit-haproxy
    image: ${HAPROXY_IMAGE}
    hostname: rabbit-haproxy.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.40
    #    command: ["-f","/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
      - 1080:1080
    volumes:
      - ${DOCKER_CONFIG}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  rabbit-1:
    &rabbitmq
    container_name: rabbit-1
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit-1.shit-code.com
    privileged: true
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    extra_hosts:
      - rabbit-1:${IP_ADDR_PREFIX}.41
      - rabbit-2:${IP_ADDR_PREFIX}.42
      - rabbit-3:${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node1:/var/lib/rabbitmq/mnesia
  rabbit-2:
    depends_on:
      - rabbit-1
    <<: *rabbitmq
    container_name: rabbit-2
    hostname: rabbit-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.42
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node2:/var/lib/rabbitmq/mnesia
  rabbit-3:
    depends_on:
      - rabbit-1
    <<: *rabbitmq
    container_name: rabbit-3
    hostname: rabbit-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node3:/var/lib/rabbitmq/mnesia

  #  rabbitmqctl stop_app
  #  rabbitmqctl reset
  #  rabbitmqctl join_cluster --ram rabbit@rabbit1
  #  rabbitmqctl start_app

  # https://www.cnblogs.com/refuge/p/10359539.html

#  HA sync mode
#manual : 手动模式(默认值) 手动模式下,新加入的节点不会同步老节点的队列(及消息)
#automatic : 自动模式
#
#HA mirror promotion on failure
#  when-synced
#  always (默认值)
#
#HA mirror promotion on shutdown
