version: '3.8'

services:
  zipkin_1:
    container_name: zipkin-1
    image: ${ZIPKIN_IMAGE}
    hostname: zipkin-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.51
  zipkin_2:
    container_name: zipkin-2
    image: ${ZIPKIN_IMAGE}
    hostname: zipkin-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.52
