version: '3.8'

services:
  logstash:
    container_name: logstash
    image: ${LOGSTASH_IMAGE}
    hostname: logstash.shit-code.com
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
      - rabbit.shit-code.com:${IP_ADDR_PREFIX}.10
#    command: ["-f","/usr/share/logstash/config/rabbitmq.conf"]
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.61
    volumes:
      - ${DOCKER_CONFIG}/logstash/rabbitmq.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${DOCKER_CONFIG}/logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ${DOCKER_CONFIG}/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
  kibana:
    container_name: kibana
    image: ${KIBANA_IMAGE}
    hostname: kibana.shit-code.com
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
    ports:
      - 5601:5601
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.69
    volumes:
      - ${DOCKER_CONFIG}/kibana/kibana:/usr/share/kibana/bin/kibana
      - ${DOCKER_CONFIG}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  elasticsearch-1:
    container_name: elasticsearch-1
    hostname: elasticsearch-1.shit-code.com
    image: ${ELASTICSEARCH_IMAGE}
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch-1
      - discovery.seed_hosts=elasticsearch-2.shit-code.com,elasticsearch-3.shit-code.com
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - cluster.name=shit-code-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      &ulimits
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_volume_1:/usr/share/elasticsearch
    #      - ${DOCKER_CONFIG}/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    #      - ${DOCKER_VOLUME}/elasticsearch/node1:/usr/share/elasticsearch/data
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.63
  elasticsearch-2:
    container_name: elasticsearch-2
    hostname: elasticsearch-2.shit-code.com
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      - node.name=elasticsearch-2
      - discovery.seed_hosts=elasticsearch-1.shit-code.com,elasticsearch-3.shit-code.com
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - cluster.name=shit-code-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      <<: *ulimits
    volumes:
      - elasticsearch_volume_2:/usr/share/elasticsearch
    #      - ${DOCKER_CONFIG}/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    #      - ${DOCKER_VOLUME}/elasticsearch/node2:/usr/share/elasticsearch/data
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.64
  elasticsearch-3:
    container_name: elasticsearch-3
    hostname: elasticsearch-3.shit-code.com
    image: ${ELASTICSEARCH_IMAGE}
    environment:
      - node.name=elasticsearch-3
      - discovery.seed_hosts=elasticsearch-1.shit-code.com,elasticsearch-2.shit-code.com
      - cluster.initial_master_nodes=elasticsearch-1,elasticsearch-2,elasticsearch-3
      - cluster.name=shit-code-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      <<: *ulimits
    volumes:
      - elasticsearch_volume_3:/usr/share/elasticsearch
    #      - ${DOCKER_CONFIG}/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    #      - ${DOCKER_VOLUME}/elasticsearch/node3:/usr/share/elasticsearch/data
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.65

volumes:
  elasticsearch_volume_1:
  elasticsearch_volume_2:
  elasticsearch_volume_3:

#/etc/sysctl.cnf
    #vm.max_map_count = 262144
  #sysctl -p
#https://www.elastic.co/guide/en/elasticsearch/reference/7.8/docker.html
#https://www.elastic.co/guide/en/logstash/current/docker.html
#https://www.elastic.co/guide/en/kibana/current/docker.html
#https://github.com/mobz/elasticsearch-head#running-with-built-in-server