version: '3.8'

services:
  grafana:
    container_name: grafana
    image: ${GRAFANA_IMAGE}
    hostname: grafana.shit-code.com
    extra_hosts:
      - prometheus.shit-code.com:${IP_ADDR_PREFIX}.71
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.70
  prometheus:
    container_name: prometheus
    image: ${PROMETHEUS_IMAGE}
    hostname: prometheus.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.71
    ports:
      - 9090:9090
    extra_hosts:
      - consul-exporter.shit-code.com:${IP_ADDR_PREFIX}.72
      - consul.shit-code.com:${IP_ADDR_PREFIX}.10
      - redis-exporter.shit-code.com:${IP_ADDR_PREFIX}.75
    volumes:
      - prometheus-volume:/prometheus
      - ${DOCKER_CONFIG}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  consul-exporter:
    container_name: consul-exporter
    image: ${PROMETHEUS_CONSUL_EXPORTER_IMAGE}
    hostname: consul-exporter.shit-code.com
    command: ['--consul.server=consul.shit-code.com:8500']
    extra_hosts:
      - consul.shit-code.com:${IP_ADDR_PREFIX}.10
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.72

  mysql-master-exporter:
    container_name: mysql-master-exporter
    image: ${PROMETHEUS_MYSQL_EXPORTER_IMAGE}
    hostname: mysql-master-exporter.shit-code.com
    extra_hosts:
      - mysql-master.shit-code.com:${IP_ADDR_PREFIX}.21
    volumes:
      - ${DOCKER_CONFIG}/prometheus/mysql/master.cnf:/home/.my.cnf
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.73

  mysql-slave-exporter:
    container_name: mysql-slave-exporter
    image: ${PROMETHEUS_MYSQL_EXPORTER_IMAGE}
    hostname: mysql-slave.shit-code.com
    extra_hosts:
      - mysql-slave.shit-code.com:${IP_ADDR_PREFIX}.22
    volumes:
      - ${DOCKER_CONFIG}/prometheus/mysql/slave.cnf:/home/.my.cnf
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.74

  redis-exporter:
    container_name: redis-exporter
    image: ${REDIS_EXPORTER_IMAGE}
    hostname: redis-exporter.shit-code.com
    extra_hosts:
      - redis-1.shit-code.com:${IP_ADDR_PREFIX}.31
      - redis-2.shit-code.com:${IP_ADDR_PREFIX}.32
      - redis-3.shit-code.com:${IP_ADDR_PREFIX}.33
      - redis-4.shit-code.com:${IP_ADDR_PREFIX}.34
      - redis-5.shit-code.com:${IP_ADDR_PREFIX}.35
      - redis-6.shit-code.com:${IP_ADDR_PREFIX}.36
    #    command: ['-redis.addr','172.28.0.71']
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.75
  haprooxy-exporter:
    container_name: haprooxy-exporter
    image: ${PROMETHEUS_HAPROXY_EXPORTER_IMAGE}
    hostname: haproxy.shit-code.com
    extra_hosts:
      - haproxy.shit-code.com:${IP_ADDR_PREFIX}.10
    command: ['--haproxy.scrape-uri=http://admin:admin@consul.shit-code.com/admin?stats;csv']
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.76
  rabbit-exporter:
    extra_hosts:
      - rabbit-1.shit-code.com:${IP_ADDR_PREFIX}.41
      - rabbit-2.shit-code.com:${IP_ADDR_PREFIX}.42
      - rabbit-3.shit-code.com:${IP_ADDR_PREFIX}.43
    container_name: rabbit-exporter
    image: ${PROMETHEUS_RABBIT_EXPORTER_IMAGE}
    hostname: rabbit-exporter.shit-code.com
    command: ["-config-file","conf/rabbit.conf"]
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.77
    volumes:
      - ${DOCKER_CONFIG}/prometheus/rabbit/rabbit.conf:/conf/rabbit.conf
  elasticsearch-exporter:
    extra_hosts:
      - elasticsearch-1.shit-code.com:${IP_ADDR_PREFIX}.63
      - elasticsearch-2.shit-code.com:${IP_ADDR_PREFIX}.64
      - elasticsearch-3.shit-code.com:${IP_ADDR_PREFIX}.65
    container_name: elasticsearch-exporter
    image: ${PROMETHEUS_ELASTICSEARCH_EXPORTER_IMAGE}
    hostname: elasticsearch-exporter.shit-code.com
    command:
      - '--es.uri=http://elasticsearch-1.shit-code.com:9200'
      - '--es.all'
      - '--es.cluster_settings'
      - '--es.indices'
      - '--es.indices_settings'
      - '--es.shards'
      - '--es.snapshots'
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.78
    volumes:
      - ${DOCKER_CONFIG}/prometheus/rabbit/rabbit.conf:/conf/rabbit.conf
volumes:
  grafana-storage:
  prometheus-volume:

#curl -X PUT -d '{"id": "mysql-master","name": "mysql-master","address": "172.28.0.73","port": 9104,"tags": ["test"],"checks": [{"http": "http://172.28.0.73:9104/","interval": "5s"}]}'     http://172.28.0.10:8500/v1/agent/service/register
#curl -X PUT -d '{"id": "consul-cluster","name": "consul-cluster","address": "172.28.0.72","port": 9107,"tags": ["test"],"checks": [{"http": "http://172.28.0.72:9107/","interval": "5s"}]}'     http://172.28.0.10:8500/v1/agent/service/register
#curl -X PUT -d '{"id": "redis-exporter","name": "redis-exporter1","address": "172.28.0.75","port": 9121,"tags": ["test"],"checks": [{"http": "http://172.28.0.75:9121/","interval": "5s"}]}'     http://172.28.0.10:8500/v1/agent/service/register

#curl -X PUT -d '{"id": "redis-1","name": "redis-1","address": "172.28.0.31","port": 6379,"tags": ["test"],"checks": [{"http": "http://172.28.0.31:6379/","interval": "5s"}]}'     http://172.28.0.10:8500/v1/agent/service/register

#https://hub.docker.com/r/prom/consul-exporter
#https://hub.docker.com/r/prom/mysqld-exporter
#https://hub.docker.com/r/prom/haproxy-exporter
#https://github.com/oliver006/redis_exporter
#https://github.com/justwatchcom/elasticsearch_exporter
#https://grafana.com/docs/grafana/latest/installation/docker/


#https://grafana.com/grafana/dashboards?search=redis&dataSource=prometheus