version: '3.8'

services:
#  grafana:
#    container_name: grafana
#    image: ${GRAFANA_IMAGE}
#    hostname: grafana.shit-code.com
#    extra_hosts:
#      - prometheus.shit-code.com:${IP_ADDR_PREFIX}.71
#    ports:
#      - 3000:3000
#    volumes:
#      - grafana-storage:/var/lib/grafana
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.70
  prometheus:
    container_name: prometheus
    image: ${PROMETHEUS_IMAGE}
    hostname: prometheus.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.71
    ports:
    - 9090:9090
    extra_hosts:
      - redis-exporter.shit-code.com:${IP_ADDR_PREFIX}.75
    volumes:
      - ${DOCKER_CONFIG}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#  prometheus-consul-exporter:
#    container_name: prometheus-consul-exporter
#    image: ${PROMETHEUS_CONSUL_EXPORTER_IMAGE}
#    hostname: prometheus-consul.shit-code.com
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.72
#  prometheus-mysql-master-exporter:
#    container_name: prometheus-mysql-master-exporter
#    image: ${PROMETHEUS_MYSQL_EXPORTER_IMAGE}
#    hostname: prometheus-mysql-master.shit-code.com
#    extra_hosts:
#      - mysql-master.shit-code.com:${IP_ADDR_PREFIX}.21
#    volumes:
#      - ${DOCKER_CONFIG}/prometheus/mysql/master.cnf:/home/.my.cnf
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.73
#  prometheus-mysql-slave-exporter:
#    container_name: prometheus-mysql-slave-exporter
#    image: ${PROMETHEUS_MYSQL_EXPORTER_IMAGE}
#    hostname: prometheus-mysql-slave.shit-code.com
#    extra_hosts:
#      - mysql-slave.shit-code.com:${IP_ADDR_PREFIX}.22
#    volumes:
#      - ${DOCKER_CONFIG}/prometheus/mysql/slave.cnf:/home/.my.cnf
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.74
#  prometheus-haprooxy-exporter:
#    container_name: prometheus-haprooxy-exporter
#    image: ${PROMETHEUS_HAPROXY_EXPORTER_IMAGE}
#    hostname: prometheus-haproxy.shit-code.com
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.74
  redis-exporter:
    container_name: redis-exporter
    image: ${REDIS_EXPORTER_IMAGE}
    hostname: redis-exporter.shit-code.com
    command: ['-redis.addr','172.28.0.71']
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.75
volumes:
  grafana-storage:

#curl -X PUT -d '{"id": "mysql-master","name": "mysql-master","address": "172.28.0.73","port": 9104,"tags": ["test"],"checks": [{"http": "http://172.28.0.73:9104/","interval": "5s"}]}'     http://172.28.0.10:8500/v1/agent/service/register

#https://hub.docker.com/r/prom/consul-exporter
#https://hub.docker.com/r/prom/mysqld-exporter
#https://hub.docker.com/r/prom/haproxy-exporter
#https://github.com/oliver006/redis_exporter
#https://github.com/justwatchcom/elasticsearch_exporter
#https://grafana.com/docs/grafana/latest/installation/docker/