version: '3.8'

x-hosts:
  &default-hosts
  extra_hosts:
    - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
    - consul-2.shit-code.com:${IP_ADDR_PREFIX}.12
    - consul-3.shit-code.com:${IP_ADDR_PREFIX}.13
    - mysql-master.shit-code.com:${IP_ADDR_PREFIX}.21
    - mysql-slave.shit-code.com:${IP_ADDR_PREFIX}.22
    - redis-1.shit-code.com:${IP_ADDR_PREFIX}.31
    - redis-2.shit-code.com:${IP_ADDR_PREFIX}.32
    - redis-3.shit-code.com:${IP_ADDR_PREFIX}.33
    - redis-4.shit-code.com:${IP_ADDR_PREFIX}.34
    - redis-5.shit-code.com:${IP_ADDR_PREFIX}.35
    - redis-6.shit-code.com:${IP_ADDR_PREFIX}.36


#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16


#consul集群配置
services:



  rabbit_haproxy:
    container_name: rabbit-haproxy
    image: ${HAPROXY_IMAGE}
    hostname: rabbit-haproxy.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.40
    #    command: ["-f","/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
      - 1080:1080
    volumes:
      - ${DOCKER_CONFIG}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  rabbit-1:
    &rabbitmq
    container_name: rabbit-1
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit-1.shit-code.com
    privileged: true
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    extra_hosts:
      - rabbit-1:${IP_ADDR_PREFIX}.41
      - rabbit-2:${IP_ADDR_PREFIX}.42
      - rabbit-3:${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node1:/var/lib/rabbitmq/mnesia
  rabbit-2:
    depends_on:
      - rabbit-1
    <<: *rabbitmq
    container_name: rabbit-2
    hostname: rabbit-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.42
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node2:/var/lib/rabbitmq/mnesia
  rabbit-3:
    depends_on:
      - rabbit-1
    <<: *rabbitmq
    container_name: rabbit-3
    hostname: rabbit-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.43
    volumes:
      - ${DOCKER_VOLUME}/rabbit/node3:/var/lib/rabbitmq/mnesia