version: '3.8'

x-hosts:
  &default-hosts
  extra_hosts:
    - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
    - consul-2.shit-code.com:${IP_ADDR_PREFIX}.12
    - consul-3.shit-code.com:${IP_ADDR_PREFIX}.13
    - mysql-master.shit-code.com:${IP_ADDR_PREFIX}.21
    - mysql-slave.shit-code.com:${IP_ADDR_PREFIX}.22
    - redis-1.shit-code.com:${IP_ADDR_PREFIX}.31
    - redis-2.shit-code.com:${IP_ADDR_PREFIX}.32
    - redis-3.shit-code.com:${IP_ADDR_PREFIX}.33
    - redis-4.shit-code.com:${IP_ADDR_PREFIX}.34
    - redis-5.shit-code.com:${IP_ADDR_PREFIX}.35
    - redis-6.shit-code.com:${IP_ADDR_PREFIX}.36


#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16


#consul集群配置
services:
  consul-1:
    &consul
    <<: *default-hosts
    container_name: consul-1
    image: ${CONSUL_IMAGE}
    hostname: consul-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent", "-config-dir", "/consul/config"]
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-2:
    <<: *consul
    container_name: consul-2
    hostname: consul-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.12
    volumes:
      - ${DOCKER_VOLUME}/consul/node2:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  consul-3:
    <<: *consul
    container_name: consul-3
    hostname: consul-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.13
    volumes:
      - ${DOCKER_VOLUME}/consul/node3:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  mysql-master:
    &mysql
    <<: *default-hosts
    container_name: mysql-master
    image: ${MYSQL_IMAGE}
    hostname: mysql-master.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.21
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    #      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_CONFIG}/mysql/master.cnf:/etc/mysql/conf.d/master.cnf
      - ${DOCKER_CONFIG}/mysql/server1.cnf:/etc/mysql/conf.d/server1.cnf
      - ${DOCKER_VOLUME}/mysql/master1:/var/lib/mysql
  mysql-slave:
    <<: *mysql
    container_name: mysql-slave
    hostname: mysql-slave-1.shit-code.com
    depends_on:
      - mysql-master
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.22
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_CONFIG}/mysql/server3.cnf:/etc/mysql/conf.d/server3.cnf
      - ${DOCKER_VOLUME}/mysql/slave1:/var/lib/mysql
  redis-1:
    &redis
    <<: *default-hosts
    container_name: redis-1
    image: ${REDIS_IMAGE}
    hostname: redis-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.31
    command: ["/usr/local/etc/redis/redis.conf"]
    volumes:
      - ${DOCKER_VOLUME}/redis/server1:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-2:
    <<: *redis
    container_name: redis-2
    hostname: redis-2.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.32
    volumes:
      - ${DOCKER_VOLUME}/redis/server2:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-3:
    <<: *redis
    container_name: redis-3
    hostname: redis-3.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.33
    volumes:
      - ${DOCKER_VOLUME}/redis/server3:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-4:
    <<: *redis
    container_name: redis-4
    hostname: redis-4.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.34
    volumes:
      - ${DOCKER_VOLUME}/redis/server4:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-5:
    <<: *redis
    container_name: redis-5
    hostname: redis-5.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.35
    volumes:
      - ${DOCKER_VOLUME}/redis/server5:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-6:
    <<: *redis
    container_name: redis-6
    hostname: redis-6.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.36
    volumes:
      - ${DOCKER_VOLUME}/redis/server6:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf