version: '3.8'

networks:
  dev-network:
    external: true

x-hosts:
  &default-hosts
  extra_hosts:
    - consul.shit-code.com:${IP_ADDR_PREFIX}.11
    - redis.shit-code.com:${IP_ADDR_PREFIX}.31
    - nginx.shit-code.com:${IP_ADDR_PREFIX}.61
    - mysql.shit-code.com:${IP_ADDR_PREFIX}.21
    - rabbit.shit-code.com:${IP_ADDR_PREFIX}.41
    - zipkin.shit-code.com:${IP_ADDR_PREFIX}.51
    - admin.shit-code.com:${IP_ADDR_PREFIX}.101
    - gateway.shit-code.com:${IP_ADDR_PREFIX}.111

services:
  admin:
    <<: *default-hosts
    container_name: admin
    image: ${ADMIN_IMAGE}
    hostname: admin.shit-code.com
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.101
    ports:
    - 8081:8080
    environment:
      - PROFILE=dev
    volumes:
      - ${DOCKER_VOLUME}/infrastructure/logs/admin:/app/log
      - ${DOCKER_CONFIG}/apps:/app/config
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/client.json:/consul/config/client.json
  gateway:
    depends_on:
      - admin
    <<: *default-hosts
    container_name: gateway
    image: ${GATEWAY_IMAGE}
    hostname: gateway.shit-code.com
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.111
    ports:
      - 8080:8080
    environment:
      - PROFILE=dev
    volumes:
      - ${DOCKER_VOLUME}/infrastructure/logs/gateway:/app/log
      - ${DOCKER_CONFIG}/apps:/app/config
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/client.json:/consul/config/client.json