version: '3.8'

#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16

services:
  consul:
    container_name: consul
    image: ${CONSUL_IMAGE}
    hostname: consul.shit-code.com
    ports:
      - 8500:8500
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
#    command: ["agent",  "-config-dir", "/consul/config"]
    command: ["agent",  "dev"]
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  mysql:
    container_name: mysql
    image: ${MYSQL_IMAGE}
    hostname: mysql.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_VOLUME}/mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: ${REDIS_IMAGE}
    hostname: redis.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.31
    ports:
      - 6379:6379
    volumes:
      - ${DOCKER_VOLUME}/redis:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  rabbit:
    container_name: rabbit
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit.shit-code.com
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    volumes:
      - ${DOCKER_VOLUME}/rabbit:/var/lib/rabbitmq
  zipkin:
    container_name: zipkin
    image: ${ZIPKIN_IMAGE}
    hostname: zipkin.shit-code.com
    ports:
      - 9411:9411
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.51
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    hostname: nginx.shit-code.com
    ports:
      - 80:80
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.61
    volumes:
      - ${DOCKER_CONFIG}/logback/logback-spring.xml:/usr/share/nginx/html/logback-spring.xml
#  git2consul:
#    depends_on:
#      - consul
#    container_name: git2consul
#    image: cimpress/git2consul
#    hostname: git2consul.shit-code.com
#    command: ['--endpoint','consul.shit-code.com','--port','8500','--config-file','/etc/git2consul.d/config.json']
#    extra_hosts:
#      - consul.shit-code.com:${IP_ADDR_PREFIX}.11
#    networks:
#      cluster-network:
#        ipv4_address: ${IP_ADDR_PREFIX}.19
#    volumes:
#      - ${DOCKER_CONFIG}/git2consul/config.json:/etc/git2consul.d/config.json
#    restart: always