spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: http://www.baidu.com/s/
          predicates:
            - Path=/*
          filters:
            - AddRequestParameter=wd, github