version: '3.8'

networks:
  cluster-network:
    external: true

x-hosts:
  &default-hosts
  extra_hosts:
    - consul-standalone.shit-code.com:${IP_ADDR_PREFIX}.11
    - redis-standalone.shit-code.com:${IP_ADDR_PREFIX}.31
    - nginx-standalone.shit-code.com:${IP_ADDR_PREFIX}.92
    - mysql-standalone.shit-code.com:${IP_ADDR_PREFIX}.21
    - rabbit-standalone.shit-code.com:${IP_ADDR_PREFIX}.41
    - zipkin-standalone.shit-code.com:${IP_ADDR_PREFIX}.51
    - admin-standalone.shit-code.com:${IP_ADDR_PREFIX}.101
    - gateway-standalone.shit-code.com:${IP_ADDR_PREFIX}.111

services:
  admin:
    <<: *default-hosts
    container_name: admin
    image: ${ADMIN_IMAGE}
    hostname: admin-standalone.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.101
    environment:
      - PROFILE=standalone
    volumes:
      - ${DOCKER_VOLUME}/infrastructure/logs/admin1:/app/log
      - ${DOCKER_CONFIG}/infrastructure/config/admin:/app/config
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/client.json:/consul/config/client.json
  gateway:
    <<: *default-hosts
    container_name: gateway
    image: ${GATEWAY_IMAGE}
    hostname: gateway-standalone.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.111
    environment:
      - PROFILE=standalone
    volumes:
      - ${DOCKER_VOLUME}/infrastructure/logs/gateway1:/app/log
      - ${DOCKER_CONFIG}/infrastructure/config/gateway:/app/config
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/client.json:/consul/config/client.json