version: '3.8'

#创建一个网络
networks:
  cluster-network:
    name: cluster-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16

x-hosts:
  &default-hosts
  extra_hosts:
    - consul-1.shit-code.com:${IP_ADDR_PREFIX}.11
    - redis-1.shit-code.com:${IP_ADDR_PREFIX}.31
    - nginx-1.shit-code.com:${IP_ADDR_PREFIX}.92
    - mysql-1.shit-code.com:${IP_ADDR_PREFIX}.21
    - rabbit-1.shit-code.com:${IP_ADDR_PREFIX}.41
    - zipkin-1.shit-code.com:${IP_ADDR_PREFIX}.51
    - admin-1.shit-code.com:${IP_ADDR_PREFIX}.101
    - gateway-1.shit-code.com:${IP_ADDR_PREFIX}.111


services:
  consul-1:
    <<: *default-hosts
    container_name: consul
    image: ${CONSUL_IMAGE}
    hostname: consul-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent",  "-config-dir", "/consul/config"]
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  redis:
    <<: *default-hosts
    container_name: redis
    image: ${REDIS_IMAGE}
    hostname: redis-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.31
    ports:
      - 6379:6379
    volumes:
      - ${DOCKER_VOLUME}/redis:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  mysql:
    <<: *default-hosts
    container_name: mysql
    image: ${MYSQL_IMAGE}
    hostname: mysql-1.shit-code.com
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_VOLUME}/mysql:/var/lib/mysql
  rabbit:
    <<: *default-hosts
    container_name: rabbit
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit-1.shit-code.com
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
  zipkin:
    <<: *default-hosts
    container_name: zipkin
    image: ${ZIPKIN_IMAGE}
    hostname: zipkin-1.shit-code.com
    ports:
      - 9411:9411
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.51
  nginx:
    <<: *default-hosts
    container_name: nginx
    image: ${NGINX_IMAGE}
    hostname: nginx-1.shit-code.com
    ports:
      - 80:80
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.92
    volumes:
      - ${DOCKER_CONFIG}/logback/logback-spring.xml:/usr/share/nginx/html/logback-spring.xml
